version: '3.9'

networks:
    nginx-php74-mariadb-pulmoinfo:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-pulmoinfo
        ports:
            - "7300:80"
        volumes:
            - ./app:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php74-service
            - mariadb
        networks:
            - nginx-php74-mariadb-pulmoinfo

    # php
    php74-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php74-pulmoinfo
        ports:
            - "9001:9000"
        volumes:
            - ./app:/var/www/project
        networks:
            - nginx-php74-mariadb-pulmoinfo

    # mysql
    mariadb:
        image: mariadb
        container_name: mariadb-pulmoinfo
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always 
        environment:
            MYSQL_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - nginx-php74-mariadb-pulmoinfo